version: '3.7'
services:
  app:
    build:
      context: .
      dockerfile: development.Dockerfile
    environment: 
      NODE_ENV: development
      BOT_TOKEN: ${BOT_TOKEN}
      WEBHOOK_HOST: ${WEBHOOK_HOST}
      WEBHOOK_PORT: ${WEBHOOK_PORT}
      WEBHOOK_PATH: ${WEBHOOK_PATH}
      IS_WEBHOOK_ENABLED: false
      DB_URL: postgres://ranks-bot:test_password@postgres/ranks_bot
    volumes:
      - ./src:/app/src

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ranks-bot
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: ranks_bot
    ports:
      - 5432:5432