version: '3.7'
services:
  app:
    image: docker.pkg.github.com/yanislav-igonin/ranks-bot/ranks-bot:latest
    networks:
      - web
    environment: 
      NODE_ENV: production
      BOT_TOKEN: ${BOT_TOKEN}
      WEBHOOK_HOST: ${WEBHOOK_HOST}
      WEBHOOK_PORT: ${WEBHOOK_PORT}
      WEBHOOK_PATH: ${WEBHOOK_PATH}
      IS_WEBHOOK_ENABLED: 'true'
      DB_URL: ${DB_URL}
      DB_SYNC: ${DB_SYNC}
      USERS: ${USERS}
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 3s
        failure_action: rollback
        order: stop-first
      restart_policy:
        condition: on-failure
        window: 10s
      placement:
        constraints:
          - node.role == manager
      labels:
        traefik.enable: "true"
        traefik.docker.network: "web"

        traefik.http.services.ranks-bot.loadbalancer.server.port: ${WEBHOOK_PORT}

        traefik.http.routers.ranks-bot-secure.entrypoints: "https"
        traefik.http.routers.ranks-bot-secure.rule: "Host(`${WEBHOOK_URL}`) && PathPrefix(`${WEBHOOK_PATH}`)"
        traefik.http.routers.ranks-bot-secure.tls: "true"
        traefik.http.routers.ranks-bot-secure.service: "ranks-bot"

networks:
  web:
    driver: overlay
    external: true
